places=['new-york', 'los-angeles', 'dubai', 'beijing', 'tokyo']
print (places)
print (sorted(places))
print (places)
print (sorted(places, reverse=True))
print (places)
places.reverse()
print (places)
places.reverse()
print (places)
places.sort()
print (places)
places.sort(reverse=True)
print (places)
china=places.pop()
print(places)
print(china)